const products = [
  // =========================
  // LIVING ROOM (1–10)
  // =========================
  {
    id: 1,
    name: "Hillsboro 84\" Recessed Arm Sofa",
    brand: "Laurel Foundry Modern Farmhouse®",
    category: "living",
    price: 699.99,
    image: "https://images.wayfair.com/sofa-hillsboro-84.jpg",
    description: "A rustic-industrial sofa with deep cushions, textured fabric, and a solid wood base.",
    rating: 4.6,
    width: 84,
    height: 35,
    depth: 36,
    sku: "LFMF-HILL-84",
    usdz: "models/living/sofa1.usdz",
    glb: "models/living/sofa1.glb"
  },
  {
    id: 2,
    name: "Benedict 48\" Solid Wood Coffee Table",
    brand: "Steelside™",
    category: "living",
    price: 289.99,
    image: "https://images.wayfair.com/coffee-benedict-48.jpg",
    description: "A reclaimed-wood coffee table with black steel legs and a rugged farmhouse look.",
    rating: 4.7,
    width: 48,
    height: 18,
    depth: 24,
    sku: "STLS-BEN-48",
    usdz: "models/living/coffee1.usdz",
    glb: "models/living/coffee1.glb"
  },
  {
    id: 3,
    name: "Aldergrove TV Stand for TVs up to 65\"",
    brand: "Gracie Oaks",
    category: "living",
    price: 459.99,
    image: "https://images.wayfair.com/tvstand-aldergrove-58.jpg",
    description: "Barn-door style TV stand with metal hardware and distressed wood finish.",
    rating: 4.5,
    width: 58,
    height: 28,
    depth: 16,
    sku: "GO-ALDER-58",
    usdz: "models/living/tv1.usdz",
    glb: "models/living/tv1.glb"
  },
  {
    id: 4,
    name: "Hillsdale End Table",
    brand: "Trent Austin Design®",
    category: "living",
    price: 159.99,
    image: "https://images.wayfair.com/endtable-hillsdale-22.jpg",
    description: "Industrial end table with an X-frame metal base and rustic wood top.",
    rating: 4.4,
    width: 22,
    height: 24,
    depth: 22,
    sku: "TAD-HILL-22",
    usdz: "models/living/end1.usdz",
    glb: "models/living/end1.glb"
  },
  {
    id: 5,
    name: "Benedict Ladder Bookshelf",
    brand: "Union Rustic",
    category: "living",
    price: 199.99,
    image: "https://images.wayfair.com/bookshelf-benedict-ladder.jpg",
    description: "Rustic ladder shelf with metal frame and reclaimed-wood shelves.",
    rating: 4.7,
    width: 25,
    height: 72,
    depth: 14,
    sku: "UR-BEN-72",
    usdz: "models/living/shelf1.usdz",
    glb: "models/living/shelf1.glb"
  },
  {
    id: 6,
    name: "Kailani Faux Leather Armchair",
    brand: "Foundstone™",
    category: "living",
    price: 349.99,
    image: "https://images.wayfair.com/chair-kailani-faux-leather.jpg",
    description: "Industrial-style armchair with cognac faux leather upholstery and metal legs.",
    rating: 4.8,
    width: 32,
    height: 34,
    depth: 30,
    sku: "FS-KAI-32",
    usdz: "models/living/chair1.usdz",
    glb: "models/living/chair1.glb"
  },
  {
    id: 7,
    name: "Hillsboro Console Table",
    brand: "Three Posts™",
    category: "living",
    price: 229.99,
    image: "https://images.wayfair.com/console-hillsboro-48.jpg",
    description: "Rustic console table with slatted lower shelf and distressed finish.",
    rating: 4.6,
    width: 48,
    height: 30,
    depth: 14,
    sku: "TP-HILL-48",
    usdz: "models/living/console1.usdz",
    glb: "models/living/console1.glb"
  },
  {
    id: 8,
    name: "Benedict Storage Trunk",
    brand: "Lark Manor™",
    category: "living",
    price: 189.99,
    image: "https://images.wayfair.com/trunk-benedict-storage.jpg",
    description: "Rustic storage trunk with metal accents and distressed wood.",
    rating: 4.5,
    width: 38,
    height: 18,
    depth: 18,
    sku: "LM-BEN-38",
    usdz: "models/living/trunk1.usdz",
    glb: "models/living/trunk1.glb"
  },
  {
    id: 9,
    name: "Industrial Floor Lamp",
    brand: "Mercury Row®",
    category: "living",
    price: 129.99,
    image: "https://images.wayfair.com/lamp-industrial-floor.jpg",
    description: "Metal floor lamp with cage shade and Edison bulb aesthetic.",
    rating: 4.4,
    width: 12,
    height: 60,
    depth: 12,
    sku: "MR-IND-60",
    usdz: "models/living/lamp1.usdz",
    glb: "models/living/lamp1.glb"
  },
  {
    id: 10,
    name: "Industrial Wall Shelf",
    brand: "Steelside™",
    category: "living",
    price: 79.99,
    image: "https://images.wayfair.com/wallshelf-industrial-24.jpg",
    description: "Rustic wall shelf with pipe-style metal brackets.",
    rating: 4.6,
    width: 24,
    height: 10,
    depth: 8,
    sku: "STLS-IND-24",
    usdz: "models/living/wallshelf1.usdz",
    glb: "models/living/wallshelf1.glb"
  },

  // =========================
  // BEDROOM (11–20)
  // =========================
  {
    id: 11,
    name: "Hillsboro Panel Bed",
    brand: "Laurel Foundry Modern Farmhouse®",
    category: "bedroom",
    price: 799.99,
    image: "https://images.wayfair.com/bed-hillsboro-panel-queen.jpg",
    description: "Rustic panel bed with tall headboard and plank details.",
    rating: 4.7,
    width: 66,
    height: 56,
    depth: 86,
    sku: "LFMF-HILL-BED-Q",
    usdz: "models/bedroom/bed1.usdz",
    glb: "models/bedroom/bed1.glb"
  },
  {
    id: 12,
    name: "Benedict 6-Drawer Dresser",
    brand: "Steelside™",
    category: "bedroom",
    price: 649.99,
    image: "https://images.wayfair.com/dresser-benedict-6drawer.jpg",
    description: "Industrial dresser with metal pulls and rustic wood drawers.",
    rating: 4.5,
    width: 60,
    height: 36,
    depth: 18,
    sku: "STLS-BEN-DR6",
    usdz: "models/bedroom/dresser1.usdz",
    glb: "models/bedroom/dresser1.glb"
  },
  {
    id: 13,
    name: "Aldergrove Nightstand",
    brand: "Gracie Oaks",
    category: "bedroom",
    price: 199.99,
    image: "https://images.wayfair.com/nightstand-aldergrove.jpg",
    description: "Rustic nightstand with drawer, shelf, and barn-door hardware.",
    rating: 4.6,
    width: 24,
    height: 26,
    depth: 16,
    sku: "GO-ALDER-NS",
    usdz: "models/bedroom/nightstand1.usdz",
    glb: "models/bedroom/nightstand1.glb"
  },
  {
    id: 14,
    name: "Industrial Metal Bed Frame",
    brand: "Trent Austin Design®",
    category: "bedroom",
    price: 499.99,
    image: "https://images.wayfair.com/bed-industrial-metal-queen.jpg",
    description: "Metal bed frame with pipe-style posts and rustic wood headboard.",
    rating: 4.4,
    width: 63,
    height: 52,
    depth: 84,
    sku: "TAD-IND-BED-Q",
    usdz: "models/bedroom/bed2.usdz",
    glb: "models/bedroom/bed2.glb"
  },
  {
    id: 15,
    name: "Benedict Sliding Door Wardrobe",
    brand: "Union Rustic",
    category: "bedroom",
    price: 899.99,
    image: "https://images.wayfair.com/wardrobe-benedict-sliding.jpg",
    description: "Large wardrobe with sliding barn doors and adjustable shelves.",
    rating: 4.3,
    width: 60,
    height: 80,
    depth: 22,
    sku: "UR-BEN-WARD",
    usdz: "models/bedroom/wardrobe1.usdz",
    glb: "models/bedroom/wardrobe1.glb"
  },
  {
    id: 16,
    name: "Kailani Upholstered Bench",
    brand: "Foundstone™",
    category: "bedroom",
    price: 229.99,
    image: "https://images.wayfair.com/bench-kailani-upholstered.jpg",
    description: "End-of-bed bench with metal legs and textured upholstery.",
    rating: 4.7,
    width: 48,
    height: 18,
    depth: 16,
    sku: "FS-KAI-BENCH",
    usdz: "models/bedroom/bench1.usdz",
    glb: "models/bedroom/bench1.glb"
  },
  {
    id: 17,
    name: "Hillsboro 5-Drawer Chest",
    brand: "Three Posts™",
    category: "bedroom",
    price: 599.99,
    image: "https://images.wayfair.com/chest-hillsboro-5drawer.jpg",
    description: "Tall chest with five drawers and rustic plank front.",
    rating: 4.5,
    width: 36,
    height: 52,
    depth: 18,
    sku: "TP-HILL-CH5",
    usdz: "models/bedroom/chest1.usdz",
    glb: "models/bedroom/chest1.glb"
  },
  {
    id: 18,
    name: "Industrial Wall Mirror",
    brand: "Lark Manor™",
    category: "bedroom",
    price: 149.99,
    image: "https://images.wayfair.com/mirror-industrial-wall.jpg",
    description: "Rectangular wall mirror with black metal frame.",
    rating: 4.6,
    width: 30,
    height: 40,
    depth: 2,
    sku: "LM-IND-MIR",
    usdz: "models/bedroom/mirror1.usdz",
    glb: "models/bedroom/mirror1.glb"
  },
  {
    id: 19,
    name: "Rustic Blanket Ladder",
    brand: "Mercury Row®",
    category: "bedroom",
    price: 89.99,
    image: "https://images.wayfair.com/ladder-rustic-blanket.jpg",
    description: "Decorative blanket ladder with distressed wood finish.",
    rating: 4.5,
    width: 20,
    height: 72,
    depth: 2,
    sku: "MR-RUST-LAD",
    usdz: "models/bedroom/ladder1.usdz",
    glb: "models/bedroom/ladder1.glb"
  },
  {
    id: 20,
    name: "Industrial Nightstand with USB",
    brand: "Steelside™",
    category: "bedroom",
    price: 179.99,
    image: "https://images.wayfair.com/nightstand-industrial-usb.jpg",
    description: "Nightstand with metal frame, rustic wood top, and built-in USB ports.",
    rating: 4.6,
    width: 22,
    height: 24,
    depth: 16,
    sku: "STLS-IND-NS-USB",
    usdz: "models/bedroom/nightstand2.usdz",
    glb: "models/bedroom/nightstand2.glb"
  },

  // =========================
  // DINING (21–30)
  // =========================
  {
    id: 21,
    name: "Hillsboro 6-Person Dining Table",
    brand: "Laurel Foundry Modern Farmhouse®",
    category: "dining",
    price: 699.99,
    image: "https://images.wayfair.com/table-hillsboro-6person.jpg",
    description: "Rectangular dining table with thick plank top and trestle base.",
    rating: 4.7,
    width: 72,
    height: 30,
    depth: 38,
    sku: "LFMF-HILL-TBL6",
    usdz: "models/dining/table1.usdz",
    glb: "models/dining/table1.glb"
  },
  {
    id: 22,
    name: "Benedict Dining Bench",
    brand: "Steelside™",
    category: "dining",
    price: 249.99,
    image: "https://images.wayfair.com/bench-benedict-dining.jpg",
    description: "Dining bench with rustic wood seat and black metal legs.",
    rating: 4.5,
    width: 60,
    height: 18,
    depth: 14,
    sku: "STLS-BEN-BENCH",
    usdz: "models/dining/bench1.usdz",
    glb: "models/dining/bench1.glb"
  },
  {
    id: 23,
    name: "Aldergrove Upholstered Dining Chair (Set of 2)",
    brand: "Gracie Oaks",
    category: "dining",
    price: 329.99,
    image: "https://images.wayfair.com/chair-aldergrove-set2.jpg",
    description: "Set of two dining chairs with upholstered seats and rustic wood frames.",
    rating: 4.6,
    width: 20,
    height: 38,
    depth: 22,
    sku: "GO-ALDER-DC2",
    usdz: "models/dining/chair1.usdz",
    glb: "models/dining/chair1.glb"
  },
  {
    id: 24,
    name: "Industrial Bar Cart",
    brand: "Trent Austin Design®",
    category: "dining",
    price: 279.99,
    image: "https://images.wayfair.com/barcart-industrial.jpg",
    description: "Rolling bar cart with metal frame, wood shelves, and locking casters.",
    rating: 4.5,
    width: 32,
    height: 36,
    depth: 16,
    sku: "TAD-IND-BC",
    usdz: "models/dining/barcart1.usdz",
    glb: "models/dining/barcart1.glb"
  },
  {
    id: 25,
    name: "Benedict Sideboard",
    brand: "Union Rustic",
    category: "dining",
    price: 799.99,
    image: "https://images.wayfair.com/sideboard-benedict.jpg",
    description: "Sideboard with sliding barn doors and interior shelving.",
    rating: 4.4,
    width: 60,
    height: 34,
    depth: 18,
    sku: "UR-BEN-SB",
    usdz: "models/dining/sideboard1.usdz",
    glb: "models/dining/sideboard1.glb"
  },
  {
    id: 26,
    name: "Kailani Counter Stools (Set of 2)",
    brand: "Foundstone™",
    category: "dining",
    price: 259.99,
    image: "https://images.wayfair.com/stools-kailani-counter-set2.jpg",
    description: "Set of two counter-height stools with faux leather seats and metal bases.",
    rating: 4.7,
    width: 18,
    height: 26,
    depth: 18,
    sku: "FS-KAI-CS2",
    usdz: "models/dining/stool1.usdz",
    glb: "models/dining/stool1.glb"
  },
  {
    id: 27,
    name: "Hillsboro Display Cabinet",
    brand: "Three Posts™",
    category: "dining",
    price: 899.99,
    image: "https://images.wayfair.com/cab
