const products = [
  // ========== LIVING ROOM (1–10) ==========
  {
    id: 1,
    name: "Hillsboro 84\" Recessed Arm Sofa",
    brand: "Laurel Foundry Modern Farmhouse®",
    category: "living",
    price: 699.99,
    image: "https://images.wayfair.com/sofa-hillsboro-84.jpg",
    description: "A rustic-industrial sofa with deep cushions, textured fabric, and a solid wood base in a warm finish.",
    rating: 4.6,
    width: 84,
    height: 35,
    depth: 36,
    sku: "LFMF-HILL-84",
    arAvailable: true,
    usdz: "models/living/sofa1.usdz",
    glb: "models/living/sofa1.glb"
  },
  {
    id: 2,
    name: "Benedict 48\" Solid Wood Coffee Table",
    brand: "Steelside™",
    category: "living",
    price: 289.99,
    image: "https://images.wayfair.com/coffee-benedict-48.jpg",
    description: "A rugged reclaimed-wood coffee table with black steel legs and a low, sturdy profile.",
    rating: 4.7,
    width: 48,
    height: 18,
    depth: 24,
    sku: "STLS-BEN-48",
    arAvailable: true,
    usdz: "models/living/coffee1.usdz",
    glb: "models/living/coffee1.glb"
  },
  {
    id: 3,
    name: "Aldergrove TV Stand for TVs up to 65\"",
    brand: "Gracie Oaks",
    category: "living",
    price: 459.99,
    image: "https://images.wayfair.com/tvstand-aldergrove-58.jpg",
    description: "Barn-door style TV stand with metal hardware, open shelving, and a distressed wood finish.",
    rating: 4.5,
    width: 58,
    height: 28,
    depth: 16,
    sku: "GO-ALDER-58",
    arAvailable: true,
    usdz: "models/living/tv1.usdz",
    glb: "models/living/tv1.glb"
  },
  {
    id: 4,
    name: "Hillsdale End Table",
    brand: "Trent Austin Design®",
    category: "living",
    price: 159.99,
    image: "https://images.wayfair.com/endtable-hillsdale-22.jpg",
    description: "Industrial end table with an X-frame metal base and rustic wood top.",
    rating: 4.4,
    width: 22,
    height: 24,
    depth: 22,
    sku: "TAD-HILL-22",
    arAvailable: true,
    usdz: "models/living/end1.usdz",
    glb: "models/living/end1.glb"
  },
  {
    id: 5,
    name: "Benedict Ladder Bookshelf",
    brand: "Union Rustic",
    category: "living",
    price: 199.99,
    image: "https://images.wayfair.com/bookshelf-benedict-ladder.jpg",
    description: "Rustic ladder bookshelf with a black metal frame and reclaimed-wood shelves.",
    rating: 4.7,
    width: 25,
    height: 72,
    depth: 14,
    sku: "UR-BEN-72",
    arAvailable: true,
    usdz: "models/living/shelf1.usdz",
    glb: "models/living/shelf1.glb"
  },
  {
    id: 6,
    name: "Kailani Faux Leather Armchair",
    brand: "Foundstone™",
    category: "living",
    price: 349.99,
    image: "https://images.wayfair.com/chair-kailani-faux-leather.jpg",
    description: "Industrial-style armchair with cognac faux leather upholstery and slim metal legs.",
    rating: 4.8,
    width: 32,
    height: 34,
    depth: 30,
    sku: "FS-KAI-32",
    arAvailable: true,
    usdz: "models/living/chair1.usdz",
    glb: "models/living/chair1.glb"
  },
  {
    id: 7,
    name: "Hillsboro Console Table",
    brand: "Three Posts™",
    category: "living",
    price: 229.99,
    image: "https://images.wayfair.com/console-hillsboro-48.jpg",
    description: "Rustic console table with a slatted lower shelf and lightly distressed finish.",
    rating: 4.6,
    width: 48,
    height: 30,
    depth: 14,
    sku: "TP-HILL-48",
    arAvailable: true,
    usdz: "models/living/console1.usdz",
    glb: "models/living/console1.glb"
  },
  {
    id: 8,
    name: "Benedict Storage Trunk",
    brand: "Lark Manor™",
    category: "living",
    price: 189.99,
    image: "https://images.wayfair.com/trunk-benedict-storage.jpg",
    description: "Rustic storage trunk with metal corner brackets and a weathered wood finish.",
    rating: 4.5,
    width: 38,
    height: 18,
    depth: 18,
    sku: "LM-BEN-38",
    arAvailable: true,
    usdz: "models/living/trunk1.usdz",
    glb: "models/living/trunk1.glb"
  },
  {
    id: 9,
    name: "Industrial Floor Lamp",
    brand: "Mercury Row®",
    category: "living",
    price: 129.99,
    image: "https://images.wayfair.com/lamp-industrial-floor.jpg",
    description: "Metal floor lamp with a cage shade and Edison-style bulb aesthetic.",
    rating: 4.4,
    width: 12,
    height: 60,
    depth: 12,
    sku: "MR-IND-60",
    arAvailable: true,
    usdz: "models/living/lamp1.usdz",
    glb: "models/living/lamp1.glb"
  },
  {
    id: 10,
    name: "Industrial Wall Shelf",
    brand: "Steelside™",
    category: "living",
    price: 79.99,
    image: "https://images.wayfair.com/wallshelf-industrial-24.jpg",
    description: "Rustic wall shelf with pipe-style metal brackets and a distressed wood plank.",
    rating: 4.6,
    width: 24,
    height: 10,
    depth: 8,
    sku: "STLS-IND-24",
    arAvailable: true,
    usdz: "models/living/wallshelf1.usdz",
    glb: "models/living/wallshelf1.glb"
  },

  // ========== BEDROOM (11–20) ==========
  {
    id: 11,
    name: "Hillsboro Panel Bed",
    brand: "Laurel Foundry Modern Farmhouse®",
    category: "bedroom",
    price: 799.99,
    image: "https://images.wayfair.com/bed-hillsboro-panel-queen.jpg",
    description: "Rustic panel bed with a tall headboard, plank details, and a warm wood tone.",
    rating: 4.7,
    width: 66,
    height: 56,
    depth: 86,
    sku: "LFMF-HILL-BED-Q",
    arAvailable: true,
    usdz: "models/bedroom/bed1.usdz",
    glb: "models/bedroom/bed1.glb"
  },
  {
    id: 12,
    name: "Benedict 6-Drawer Dresser",
    brand: "Steelside™",
    category: "bedroom",
    price: 649.99,
    image: "https://images.wayfair.com/dresser-benedict-6drawer.jpg",
    description: "Industrial dresser with metal pulls, black frame, and rustic wood drawer fronts.",
    rating: 4.5,
    width: 60,
    height: 36,
    depth: 18,
    sku: "STLS-BEN-DR6",
    arAvailable: true,
    usdz: "models/bedroom/dresser1.usdz",
    glb: "models/bedroom/dresser1.glb"
  },
  {
    id: 13,
    name: "Aldergrove Nightstand",
    brand: "Gracie Oaks",
    category: "bedroom",
    price: 199.99,
    image: "https://images.wayfair.com/nightstand-aldergrove.jpg",
    description: "Rustic nightstand with one drawer, open shelf, and barn-door inspired hardware.",
    rating: 4.6,
    width: 24,
    height: 26,
    depth: 16,
    sku: "GO-ALDER-NS",
    arAvailable: true,
    usdz: "models/bedroom/nightstand1.usdz",
    glb: "models/bedroom/nightstand1.glb"
  },
  {
    id: 14,
    name: "Industrial Metal Bed Frame",
    brand: "Trent Austin Design®",
    category: "bedroom",
    price: 499.99,
    image: "https://images.wayfair.com/bed-industrial-metal-queen.jpg",
    description: "Metal bed frame with pipe-style posts and a rustic wood headboard panel.",
    rating: 4.4,
    width: 63,
    height: 52,
    depth: 84,
    sku: "TAD-IND-BED-Q",
    arAvailable: true,
    usdz: "models/bedroom/bed2.usdz",
    glb: "models/bedroom/bed2.glb"
  },
  {
    id: 15,
    name: "Benedict Sliding Door Wardrobe",
    brand: "Union Rustic",
    category: "bedroom",
    price: 899.99,
    image: "https://images.wayfair.com/wardrobe-benedict-sliding.jpg",
    description: "Large wardrobe with sliding barn doors, hanging space, and adjustable shelves.",
    rating: 4.3,
    width: 60,
    height: 80,
    depth: 22,
    sku: "UR-BEN-WARD",
    arAvailable: true,
    usdz: "models/bedroom/wardrobe1.usdz",
    glb: "models/bedroom/wardrobe1.glb"
  },
  {
    id: 16,
    name: "Kailani Upholstered Bench",
    brand: "Foundstone™",
    category: "bedroom",
    price: 229.99,
    image: "https://images.wayfair.com/bench-kailani-upholstered.jpg",
    description: "End-of-bed bench with metal legs and textured neutral upholstery.",
    rating: 4.7,
    width: 48,
    height: 18,
    depth: 16,
    sku: "FS-KAI-BENCH",
    arAvailable: true,
    usdz: "models/bedroom/bench1.usdz",
    glb: "models/bedroom/bench1.glb"
  },
  {
    id: 17,
    name: "Hillsboro 5-Drawer Chest",
    brand: "Three Posts™",
    category: "bedroom",
    price: 599.99,
    image: "https://images.wayfair.com/chest-hillsboro-5drawer.jpg",
    description: "Tall chest with five drawers, metal pulls, and a rustic plank front.",
    rating: 4.5,
    width: 36,
    height: 52,
    depth: 18,
    sku: "TP-HILL-CH5",
    arAvailable: true,
    usdz: "models/bedroom/chest1.usdz",
    glb: "models/bedroom/chest1.glb"
  },
  {
    id: 18,
    name: "Industrial Wall Mirror",
    brand: "Lark Manor™",
    category: "bedroom",
    price: 149.99,
    image: "https://images.wayfair.com/mirror-industrial-wall.jpg",
    description: "Rectangular wall mirror with a black metal frame and subtle rivet details.",
    rating: 4.6,
    width: 30,
    height: 40,
    depth: 2,
    sku: "LM-IND-MIR",
    arAvailable: true,
    usdz: "models/bedroom/mirror1.usdz",
    glb: "models/bedroom/mirror1.glb"
  },
  {
    id: 19,
    name: "Rustic Blanket Ladder",
    brand: "Mercury Row®",
    category: "bedroom",
    price: 89.99,
    image: "https://images.wayfair.com/ladder-rustic-blanket.jpg",
    description: "Decorative blanket ladder with a distressed wood finish and slim profile.",
    rating: 4.5,
    width: 20,
    height: 72,
    depth: 2,
    sku: "MR-RUST-LAD",
    arAvailable: true,
    usdz: "models/bedroom/ladder1.usdz",
    glb: "models/bedroom/ladder1.glb"
  },
  {
    id: 20,
    name: "Industrial Nightstand with USB",
    brand: "Steelside™",
    category: "bedroom",
    price: 179.99,
    image: "https://images.wayfair.com/nightstand-industrial-usb.jpg",
    description: "Nightstand with metal frame, rustic wood top, and built-in USB charging ports.",
    rating: 4.6,
    width: 22,
    height: 24,
    depth: 16,
    sku: "STLS-IND-NS-USB",
    arAvailable: true,
    usdz: "models/bedroom/nightstand2.usdz",
    glb: "models/bedroom/nightstand2.glb"
  },

  // ========== DINING (21–30) ==========
  {
    id: 21,
    name: "Hillsboro 6-Person Dining Table",
    brand: "Laurel Foundry Modern Farmhouse®",
    category: "dining",
    price: 699.99,
    image: "https://images.wayfair.com/table-hillsboro-6person.jpg",
    description: "Rectangular dining table with a thick plank top and trestle-style base.",
    rating: 4.7,
    width: 72,
    height: 30,
    depth: 38,
    sku: "LFMF-HILL-TBL6",
    arAvailable: true,
    usdz: "models/dining/table1.usdz",
    glb: "models/dining/table1.glb"
  },
  {
    id: 22,
    name: "Benedict Dining Bench",
    brand: "Steelside™",
    category: "dining",
    price: 249.99,
    image: "https://images.wayfair.com/bench-benedict-dining.jpg",
    description: "Dining bench with a rustic wood seat and black metal legs.",
    rating: 4.5,
    width: 60,
    height: 18,
    depth: 14,
    sku: "STLS-BEN-BENCH",
    arAvailable: true,
    usdz: "models/dining/bench1.usdz",
    glb: "models/dining/bench1.glb"
  },
  {
    id: 23,
    name: "Aldergrove Upholstered Dining Chair (Set of 2)",
    brand: "Gracie Oaks",
    category: "dining",
    price: 329.99,
    image: "https://images.wayfair.com/chair-aldergrove-set2.jpg",
    description: "Set of two dining chairs with upholstered seats and rustic wood frames.",
    rating: 4.6,
    width: 20,
    height: 38,
    depth: 22,
    sku: "GO-ALDER-DC2",
    arAvailable: true,
    usdz: "models/dining/chair1.usdz",
    glb: "models/dining/chair1.glb"
  },
  {
    id: 24,
    name: "Industrial Bar Cart",
    brand: "Trent Austin Design®",
    category: "dining",
    price: 279.99,
    image: "https://images.wayfair.com/barcart-industrial.jpg",
    description: "Rolling bar cart with metal frame, wood shelves, and locking casters.",
    rating: 4.5,
    width: 32,
    height: 36,
    depth: 16,
    sku: "TAD-IND-BC",
    arAvailable: true,
    usdz: "models/dining/barcart1.usdz",
    glb: "models/dining/barcart1.glb"
  },
  {
    id: 25,
    name: "Benedict Sideboard",
    brand: "Union Rustic",
    category: "dining",
    price: 799.99,
    image: "https://images.wayfair.com/sideboard-benedict.jpg",
    description: "Sideboard with sliding barn doors, interior shelving, and metal hardware.",
    rating: 4.4,
    width: 60,
    height: 34,
    depth: 18,
    sku: "UR-BEN-SB",
    arAvailable: true,
    usdz: "models/dining/sideboard1.usdz",
    glb: "models/dining/sideboard1.glb"
  },
  {
    id: 26,
    name: "Kailani Counter Stools (Set of 2)",
    brand: "Foundstone™",
    category: "dining",
    price: 259.99,
    image: "https://images.wayfair.com/stools-kailani-counter-set2.jpg",
    description: "Set of two counter-height stools with faux leather seats and metal bases.",
    rating: 4.7,
    width: 18,
    height: 26,
    depth: 18,
    sku: "FS-KAI-CS2",
    arAvailable: true,
    usdz: "models/dining/stool1.usdz",
    glb: "models/dining/stool1.glb"
  },
  {
    id: 27,
    name: "Hillsboro Display Cabinet",
    brand: "Three Posts™",
    category: "dining",
    price: 899.99,
    image: "https://images.wayfair.com/cabinet-hillsboro-display.jpg",
    description: "Tall display cabinet with glass doors, interior shelves, and rustic trim.",
    rating: 4.6,
    width: 36,
    height: 78,
    depth: 16,
    sku: "TP-HILL-CAB",
    arAvailable: true,
    usdz: "models/dining/cabinet1.usdz",
    glb: "models/dining/cabinet1.glb"
  },
  {
    id: 28,
    name: "Industrial Wine Rack",
    brand: "Lark Manor™",
    category: "dining",
    price: 169.99,
    image: "https://images.wayfair.com/winerack-industrial.jpg",
    description: "Wall-mounted wine rack with metal frame and wood shelves.",
    rating: 4.5,
    width: 24,
    height: 36,
    depth: 8,
    sku: "LM-IND-WR",
    arAvailable: true,
    usdz: "models/dining/winerack1.usdz",
    glb: "models/dining/winerack1.glb"
  },
  {
    id: 29,
    name: "Rustic Wall Clock",
    brand: "Mercury Row®",
    category: "dining",
    price: 99.99,
    image: "https://images.wayfair.com/clock-rustic-wall.jpg",
    description: "Oversized wall clock with wood face and metal numerals.",
    rating: 4.4,
    width: 30,
    height: 30,
    depth: 2,
    sku: "MR-RUST-CLK",
    arAvailable: true,
    usdz: "models/dining/clock1.usdz",
    glb: "models/dining/clock1.glb"
  },
  {
    id: 30,
    name: "Industrial Pendant Light",
    brand: "Steelside™",
    category: "dining",
    price: 149.99,
    image: "https://images.wayfair.com/pendant-industrial.jpg",
    description: "Single pendant light with metal shade and chain suspension.",
    rating: 4.6,
    width: 14,
    height: 12,
    depth: 14,
    sku: "STLS-IND-PEND",
    arAvailable: true,
    usdz: "models/dining/pendant1.usdz",
    glb: "models/dining/pendant1.glb"
  },

  // ========== OUTDOOR (31–40) ==========
  {
    id: 31,
    name: "Hillsboro Outdoor Sofa",
    brand: "Laurel Foundry Modern Farmhouse®",
    category: "outdoor",
    price: 899.99,
    image: "https://images.wayfair.com/outdoor-sofa-hillsboro.jpg",
    description: "Outdoor sofa with weather-resistant cushions and a rustic wood-look frame.",
    rating: 4.6,
    width: 78,
    height: 32,
    depth: 34,
    sku: "LFMF-HILL-OUT-SOFA",
    arAvailable: true,
    usdz: "models/outdoor/sofa1.usdz",
    glb: "models/outdoor/sofa1.glb"
  },
  {
    id: 32,
    name: "Benedict Outdoor Coffee Table",
    brand: "Steelside™",
    category: "outdoor",
    price: 249.99,
    image: "https://images.wayfair.com/outdoor-coffee-benedict.jpg",
    description: "Outdoor coffee table with slatted top and powder-coated metal frame.",
    rating: 4.5,
    width: 42,
    height: 18,
    depth: 24,
    sku: "STLS-BEN-OUT-CT",
    arAvailable: true,
    usdz: "models/outdoor/coffee1.usdz",
    glb: "models/outdoor/coffee1.glb"
  },
  {
    id: 33,
    name: "Aldergrove Adirondack Chairs (Set of 2)",
    brand: "Gracie Oaks",
    category: "outdoor",
    price: 329.99,
    image: "https://images.wayfair.com/outdoor-adirondack-aldergrove-set2.jpg",
    description: "Set of two Adirondack chairs with a rustic wood-look finish.",
    rating: 4.7,
    width: 30,
    height: 38,
    depth: 34,
    sku: "GO-ALDER-ADIR2",
    arAvailable: true,
    usdz: "models/outdoor/chair1.usdz",
    glb: "models/outdoor/chair1.glb"
  },
  {
    id: 34,
    name: "Industrial Fire Pit Table",
    brand: "Trent Austin Design®",
    category: "outdoor",
    price: 599.99,
    image: "https://images.wayfair.com/outdoor-firepit-industrial.jpg",
    description: "Gas fire pit table with a metal base and rustic wood-look top.",
    rating: 4.4,
    width: 42,
    height: 24,
    depth: 42,
    sku: "TAD-IND-FP",
    arAvailable: true,
    usdz: "models/outdoor/firepit1.usdz",
    glb: "models/outdoor/firepit1.glb"
  },
  {
    id: 35,
    name: "Benedict Outdoor Dining Table",
    brand: "Union Rustic",
    category: "outdoor",
    price: 749.99,
    image: "https://images.wayfair.com/outdoor-table-benedict.jpg",
    description: "Rectangular outdoor dining table with a plank top and sturdy legs.",
    rating: 4.5,
    width: 72,
    height: 30,
    depth: 38,
    sku: "UR-BEN-OUT-TBL",
    arAvailable: true,
    usdz: "models/outdoor/table1.usdz",
    glb: "models/outdoor/table1.glb"
  },
  {
    id: 36,
    name: "Kailani Outdoor Lounge Chair",
    brand: "Foundstone™",
    category: "outdoor",
    price: 299.99,
    image: "https://images.wayfair.com/outdoor-lounge-kailani.jpg",
    description: "Outdoor lounge chair with metal frame and thick, weather-resistant cushions.",
    rating: 4.6,
    width: 30,
    height: 32,
    depth: 34,
    sku: "FS-KAI-OUT-LC",
    arAvailable: true,
    usdz: "models/outdoor/lounge1.usdz",
    glb: "models/outdoor/lounge1.glb"
  },
  {
    id: 37,
    name: "Hillsboro Outdoor Storage Bench",
    brand: "Three Posts™",
    category: "outdoor",
    price: 279.99,
    image: "https://images.wayfair.com/outdoor-storagebench-hillsboro.jpg",
    description: "Outdoor storage bench with lift-up seat and slatted front.",
    rating: 4.5,
    width: 50,
    height: 24,
    depth: 20,
    sku: "TP-HILL-OUT-BENCH",
    arAvailable: true,
    usdz: "models/outdoor/bench1.usdz",
    glb: "models/outdoor/bench1.glb"
  },
  {
    id: 38,
    name: "Industrial Outdoor Lantern Set",
    brand: "Lark Manor™",
    category: "outdoor",
    price: 119.99,
    image: "https://images.wayfair.com/outdoor-lantern-industrial-set.jpg",
    description: "Set of two metal lanterns with glass panels and rustic finish.",
    rating: 4.6,
    width: 10,
    height: 18,
    depth: 10,
    sku: "LM-IND-OUT-LAN",
    arAvailable: true,
    usdz: "models/outdoor/lantern1.usdz",
    glb: "models/outdoor/lantern1.glb"
  },
  {
    id: 39,
    name: "Rustic Outdoor Planter Box",
    brand: "Mercury Row®",
    category: "outdoor",
    price: 89.99,
    image: "https://images.wayfair.com/outdoor-planter-rustic.jpg",
    description: "Rectangular planter box with a distressed wood-look finish.",
    rating: 4.4,
    width: 30,
    height: 18,
    depth: 12,
    sku: "MR-RUST-OUT-PLN",
    arAvailable: true,
    usdz: "models/outdoor/planter1.usdz",
    glb: "models/outdoor/planter1.glb"
  },
  {
    id: 40,
    name: "Industrial Outdoor Wall Sconce",
    brand: "Steelside™",
    category: "outdoor",
    price: 139.99,
    image: "https://images.wayfair.com/outdoor-sconce-industrial.jpg",
    description: "Outdoor wall sconce with metal shade and clear glass enclosure.",
    rating: 4.6,
    width: 8,
    height: 14,
    depth: 10,
    sku: "STLS-IND-OUT-SC",
    arAvailable: true,
    usdz: "models/outdoor/sconce1.usdz",
    glb: "models/outdoor/sconce1.glb"
  }
];

export default products;
